@startuml API. Диаграмма компонентов
title "C4. Компоненты"

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"
!include $ICONURL/common.puml
!include $ICONURL/devicons/react.puml
!include $ICONURL/devicons/go.puml
!include $ICONURL/devicons2/sqlite.puml

Component(frontend, "Мобильное приложение", "React Native", $sprite="react")

System_Boundary(taxiService, "API") {

  Component(orderController, "OrderController", "Go", "Управление заказами")
  Rel(frontend, orderController, "")
  Component(orderService, "OrderService", "Go", "Обработка заказов")
  Rel(orderController, orderService, "")
  Component(driverRepository, "DriverRepository", "Go", "Информация о водителях")
  Rel(orderService, driverRepository, "")
  
  Component(paymentController, "PaymentController", "Go", "Обработка платежей")
  Rel(frontend, paymentController, "")
  Component(paymentService, "PaymentService", "Go", "Обработка транзакций")
  Rel(paymentController, paymentService, "")
  Component(paymentRepository, "PaymentRepository", "Go", "История платежей")
  Rel(paymentService, paymentRepository, "")

  Component(photoControlController, "PhotoControlController", "Go", "Отправка фото документов")
  Rel(frontend, photoControlController, "")
  Component(photoControlService, "PhotoControlService", "Go", "Обработка фото документов")
  Rel(photoControlController, photoControlService, "")

  Component(userController, "UserController", "Go", "Управление пользователями")
  Rel(frontend, userController, "")
  Component(userService, "UserService", "Go", "Регистрация и аутентификация пользователей")
  Rel(userController, userService, "")
  Component(userRepository, "UserRepository", "Go", "Информация о пользователях")
  Rel(userService, userRepository, "")
  
  Component(loggingController, "LoggingController", "Go", "Запись логов")
  Rel(orderService, loggingController, "")
  Rel(paymentService, loggingController, "")
  Rel(photoControlService, loggingController, "")
  Rel(loggingController, loggingService, "Записывает события", "HTTPS/REST")

  Component(analyticsController, "AnalyticsController", "Go", "Получение аналитики")
  Rel(admin, analyticsController, "")
  Component(analyticsService, "AnalyticsService", "Go", "Обработка аналитики")
  Rel(analyticsController, analyticsService, "")
}

System_Ext(paymentSystem, "Платежная система", "Обработка платежей")
Rel(paymentService, paymentSystem, "Обработка транзакций", "HTTPS/REST")

System_Ext(orderDistribution, "Система распределения заказов", "Распределение заказов среди водителей")
Rel(orderService, orderDistribution, "Отправка информации о заказах", "HTTPS/REST")

System_Ext(photoControl, "Система фотоконтроля", "Отправка фото документов водителями")
Rel(photoControlService, photoControl, "Отправка фото документов", "HTTPS/REST")

@enduml